-- Delete tables if exist
USE MetroDB

DROP TABLE IF EXISTS Transfers
DROP TABLE IF EXISTS Stocks
DROP TABLE IF EXISTS WorkersPlaces

DROP TABLE IF EXISTS Trains
DROP TABLE IF EXISTS Workers

DROP TABLE IF EXISTS Depots
DROP TABLE IF EXISTS Stations
DROP TABLE IF EXISTS Lines
